# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
